baseURL = 'https://prgmr.dev/'
languageCode = 'en-us'
title = "Jinuk's Log"
theme = "paper"

# Google Analytics
googleAnalytics = 'G-ELE1RPQW86'

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
